-- Question 1
-- max is 10h per week
-- we are using mock date range to not return null value

WITH OP_IN_THE_WEEK AS
	(SELECT AMBULANCIER_ID,
			DURATION
		FROM AMBULANCESYSTEM.INTERVENTION
		WHERE INTERVENTION_DATE BETWEEN '2022-04-18' AND '2022-04-25' ),
	HEURE_CUMULEE AS
	(SELECT AMBULANCIER_ID,
			(SUM(DURATION) / 60) AS TIME_IN_HOURS_THIS_WEEK
		FROM OP_IN_THE_WEEK
		GROUP BY AMBULANCIER_ID),
	BY_BASE AS
	(SELECT HEURE_CUMULEE.AMBULANCIER_ID,
			BASE_ID
		FROM HEURE_CUMULEE
		JOIN AMBULANCESYSTEM.AMBULANCIER ON HEURE_CUMULEE.AMBULANCIER_ID = AMBULANCIER.AMBULANCIER_ID),
	GETCOUNT AS
	(SELECT BASE_ID,
			COUNT(AMBULANCIER_ID) AS AMBULANCIER_DISPONIBLE
		FROM BY_BASE
		GROUP BY BASE_ID)
SELECT BASE_NAME,
	AMBULANCIER_DISPONIBLE
FROM GETCOUNT
JOIN AMBULANCESYSTEM.BASE ON GETCOUNT.BASE_ID = BASE.BASE_ID